#!/bin/bash
set -e
if ! [ -d /etc/apt ]
then
	echo "Your operating seems not to be supported"
	echo "Can only run on Debian based system as Debian, Ubuntu, Linux Mint, ..."
	exit 1
fi
echo "This will add the netsimlan respository to your system and install netsimlan."
read -s -r -p "Press ENTER to continue or Ctrl-C to abort."
echo # simple newline because read doesn't this way

sudo apt-key add - << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBF596vIBDADpBfjLdnGVuuhVBDiG2eFDi91IRrzE+KVNpjoTeUWS76VNGicc
qhOsZHbHPt0/7MF/gX6PqQ73c98o+7wDosQc1aFVqN7fy7S2Iaj8mHpm+6bve+iu
wLtzQhb9aM6kiprX0Fp8FBFn2pfCoFs1g8jkAl4rY1y97CuBwQBTNmznsXPy9RGz
ovERYXJGnIGnP/NYfFxnALyrwquWvdtIKyjee+c3Mnht8UWoK3KGhH/ZS1e1U5uk
dcGZUOldn5LhuKd1raUuTQjU+bP4inFlFm+QGA5oIZEFLKintve3UGdThrMmS2r1
wjhKN21idD7r3iDyzZtWqm7+5046iH6ChhHbFKw6G8zj4d7sQGrKEg5t1ME6s5pX
gMFdjpnrtGH5gE28HkU2hpVXegc7y0th4aYVSmGThnca2AO9x60syPwxKE6Ienjc
4hWMy5JTUUqqMYJTyGg9m5GpbZ8APNJIGLl6HIWwTaSq1aU+Z6F1j4hjUL8NUV46
pBAH8LnyKivGQtMAEQEAAbQjTmV0U2ltTGFuIFRlYW0gPGluZm9AbmV0c2ltbGFu
Lm9yZz6JAdQEEwEKAD4CGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AWIQTgy/Y8
OEkI32XLx0vKN0G/IMc/pwUCYHBN8AUJFL5l/gAKCRDKN0G/IMc/pyQEDACe85QE
JDIU1FENag7wr6PdHpSD+D0jGdubceVNEP0TmpYCOneTGksr7YC6xJIQ/kT3XW2u
m4BJWOEP9R8wOq6VVEVWDs/oFbMt6PkKG0BU0yZlZmR1pdyRjDjfkASn9BhBAu5g
pAmY28topKHgEP7vraGKaj9yk1I8mJaB17zKRkLH7zigq1vDLU9XqkDa5/QDFx8w
7umJQgT5Ku5KbWZs9tJ9gYeF6LJtFrW7gwJCqdMF1mq6S0FyFekx4dSiCIsEK1TQ
dsPVnEQ+z2Z2p1KBu9HHkGBEozibhe8VT9pG0MUB7Wv/369CvDBNYdwW/D6RWg8a
YPnqKe8wN9Rkk8EoIcMoNH3jb1iUFtxi5z/wT7M+hV1AliSKWCFNFdzW+bVglywO
Do5+s5DDiG274UkJcJGC3up0jHvD7QIFZSGTa8rPI7Q5G3O3zqv4EpPcbLHzR4xG
0PNcg9sUS33XSmjg5/ZFDTP4hVyYAZY9tBbtjDDnn47YA4UzxWxbbd46LyG5AY0E
Xn3q8gEMALVx9Axhn+XBBIfFeGabcUl6NMhU8v+tSzfWwJMt8g/AYlhMNFTN23f/
k9suYWK4Lb9fRuT77PSIuLdBAptkmSbjGGAIXZTlDnkBNGUKMYM2x02ZadS7IJe3
Be+6GxV6gZSmI15YZdLkIJIDDXiuROUiG8LOBxTulUlu25hv5StsMtJyny73XbW6
3bsrMbX583IZ8zZV3+jEDismbQVMC7uSacHfX7cXvX1uFn2pWfvPJ/5jUYt9N4ST
JEhy1yUOyspd3RaKoIlH3XL4j6jyk/RygqbSHA3RBPypzAuQSiWL+/3tm/r9/4Tz
0cDbWzkQ4ldLn2nUKXHYit3JYXeTtDYB6ucte7Q/xJfZpwyM1ZbvZ6/4nIa74FGp
wDbio3dGOr6qUimDBddLxZz5Q6Qtz90gmzEs4o1q5vxNuEHJF0aqFrNRFrSiwM2Q
iFz0cOzErmwAF8eviIQgp0QrwuPEJ5JEyMallat1OzvDsoXCgUrTY6xFYW/KHST4
Lfo6lRv7KQARAQABiQG8BBgBCgAmAhsMFiEE4Mv2PDhJCN9ly8dLyjdBvyDHP6cF
AmBwTgIFCRS+ZhAACgkQyjdBvyDHP6e5EAwAra0clY5yipIZ+zzUUOhtpgSoTBk6
TwpulhUNuAb690vC/M9Y46itjoLMH+3xT8CF6cpuGQpK19nnr564cxlcdLLe4LhO
3laamgp/Tg2r32xw6Sf0TX4/IZHPRgB4F22dXZNtsfcUH0SGYX6f2dyHI9SqMmTU
r70uKjQ8+2RQsTNEO810g49V5rA2mRvxi4O1jcp7x2bISk3PkZ3kM29AhNdmbTqj
7XASrO/yWdK+MnFWz83zMqCCKgLHJAA3JdfIL0rgL+OpwBHkzlbMnwdl/3S0vhbD
xO6H8RcMKHY1s0RQrpaISQ2gt089yPNxa+l/Ht0nDJWDBNx1fh3pKdYjtO0mDSfP
UzSl+5YRgbyAWiA0NRM72WL+Tc8krEXPdf7AAu3TcyrokdqklAGB0t+QF/xn5U53
1KJoI6gAH15KIqcMBDqzDh0UCcN2QTBsdJK2EoZPGHFDLp8V3VaF3oz92fIr+N1p
hbuBHTRZiZyf5Mm0vhmn9QBHzN4FLs4UkUYm
=co2n
-----END PGP PUBLIC KEY BLOCK-----
EOF
sudo sh -c 'echo "deb https://apt.netsimlan.org/netsimlan latest main" > /etc/apt/sources.list.d/netsimlan.list'
sudo apt-get update || ( sudo apt-get -y install apt-transport-https && sudo apt-get update )
[[ "$(read -e -p 'Do you want to install a graphical launcher? [y/N]> '; echo $REPLY)" == [Yy]* ]] && \
	sudo apt-get -y install netsimlan-launcher || \
	sudo apt-get -y install netsimlan
